### NumPy

### Задание 1

1. Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
Создать 5 двумерных массивов разной формы из массива a. 
Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [2]:
import numpy as np
import pandas as pd

a = np.arange(12, 24, 1)
a1 = a.reshape(2, 6)
a2 = a.reshape(6, 2)
a3 = a.reshape(3, 4)
a4 = a.reshape(4, 3)
a5 = a.reshape(12, 1)

b = a.reshape(12, -1)
b1 = a.reshape(4, -1)
b2 = a.reshape(6, -1)
b3 = a.reshape(-1, 6)
b4 = a.reshape(-1, 3)

print(f"размерность массива а = {a.ndim}, а размерность массива b = {b3.ndim} - соответственно массив b не одномерный")


размерность массива а = 1, а размерность массива b = 2 - соответственно массив b не одномерный


2. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения  со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [81]:
a = np.random.randn(3, 4)
b = a.flatten()
print(b, a.size==b.size, sep="\n")


[-0.60170661  1.85227818 -0.01349722 -1.05771093  0.82254491 -1.22084365
  0.2088636  -1.95967012 -1.32818605  0.19686124  0.73846658  0.17136828]
True


3. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. 
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
В чем разница между массивами a и b?

In [43]:
a = np.arange(20, 0, -2)
b = np.arange(20, 1, -2)
print(f"Разница между массивами a и b:\n по размерности - {not(a.shape == b.shape)}; \n по типу - {not(type(a) == type(b))}")


Разница между массивами a и b:
 по размерности - False; 
 по типу - False


4. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [50]:
a = np.random.randint(0, 100, (2, 2))
b = np.random.sample((3, 2))
c = np.vstack((a, b))
print(f"объединенная матрица c: \n {c} \n размер матрицы: {c.size}")


объединенная матрица c: 
 [[ 62.           6.        ]
 [ 15.          26.        ]
 [  0.94508479   0.2169694 ]
 [  0.81990794   0.93222168]
 [  0.80947799   0.68291165]] 
 размер матрицы: 10


5. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.
Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [8]:
a = np.arange(12)
A = a.reshape(4, 3)
At = A.T
B = np.dot(A, At)
print(f"Полученная матрица B: {B} \n Размер матрицы B: {B.shape} \n Определитель марицы: {np.linalg.det(B)}")
print("Так как определитель матрицы равен 0, то данная матрица является вырожденной и вычислить обратрую к ней матрицу нельзя!")

Полученная матрица B: [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]] 
 Размер матрицы B: (4, 4) 
 Определитель марицы: 0.0
Так как определитель матрицы равен 0, то данная матрица является вырожденной и вычислить обратрую к ней матрицу нельзя!


6. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C. 
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [32]:
np.random.seed(42)
c = np.random.randint(0, 16, 16)
C = c.reshape(4, 4)
D = np.add(np.dot(C, 10), B)
D_inv = np.linalg.inv(D)
print(f"Полученная матрица D:\n {D} \n Определитель марицы D = {np.linalg.det(D)} \n Ранг матрицы D = {np.linalg.matrix_rank(D)}")
print(f"Обратная к D матрица D_inv:\n {D_inv}")

Полученная матрица D:
 [[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]] 
 Определитель марицы D = -28511999.999999944 
 Ранг матрицы D = 4
Обратная к D матрица D_inv:
 [[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


7. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. 
С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [33]:
# E_inv = [1 if el > 1 else 0 for el in D_inv]
for i in range(len(D_inv)):
    D_inv[i] = [1 if el > 0 else 0 for el in D_inv[i]]
print(f"Матрица D_inv: \n {D_inv} \n матрица B: \n {B} \n матрица C: \n {C}")
print(f"Результирующая матрица E: \n {np.where(D_inv, B, C)}")

Матрица D_inv: 
 [[ 1.  1.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  1.  0.]] 
 матрица B: 
 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]] 
 матрица C: 
 [[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
Результирующая матрица E: 
 [[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]


### Задание 2

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [86]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]).T
mean_a = np.mean(a, axis=0)
mean_a

array([ 2. ,  8.4])

### Задание 3

Вычислите массив a_centered, отняв от значений массива а средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [87]:
a_centred = np.subtract(a, mean_a)
a_centred

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 4

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [88]:
a_centred_sp = np.dot(a_centred.T[0], a_centred.T[1])
print(f"Итоговое значение: \n {a_centred_sp/(5-1)}")

Итоговое значение: 
 2.0


### Задание 5**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве а. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. 
В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.
Подробнее узнать о ковариации можно здесь:
[Ссылка](https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html)

In [89]:
np.cov(a.T)

array([[ 1. ,  2. ],
       [ 2. ,  4.3]])

### Pandas

### Задание 1

A. Импортируйте библиотеку Pandas и дайте ей псевдоним pd.
B. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные:
[1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
C. Затем создайте датафрейм book cо столбцами author_id, book_title и price,в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [11]:
authors = pd.DataFrame({"author_id":[1, 2, 3],
                         "author_name":["Тургенев", "Чехов", "Островский"]},
                       columns=["author_id", "author_name"])
books = pd.DataFrame({"author_id":[1, 1, 1, 2, 2, 3, 3],
                    "book_title":["Отцы и дети", "Рудин", "Дворянское гнездо", "Толстый и тонкий", "Дама с собачкой",
                                "Гроза", "Таланты и поклонники"],
                     "price":[450, 300, 350, 500, 450, 370, 290]},
                    columns=["author_id", "book_title", "price"])
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [46]:
authors_price = pd.merge(authors, books, on="author_id", how="inner")
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [24]:
top5 = authors_price.sort_values(by = "price", ascending=False).head(5)
top5.reset_index(drop=True, inplace=True)
top5

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

### Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price.
В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно имя автора, минимальная,
максимальная и средняя цена на книги этого автора.

In [74]:
authors_stat = pd.DataFrame({"author_name":[], "min_price":[], "max_price":[], "mean_price":[]},
                            columns=["author_name", "min_price", "max_price", "mean_price"])
i = 0
for auth in authors_price["author_name"].unique():
    authors_stat.loc[i, "author_name"] = auth
    authors_stat.loc[i, "min_price"] = authors_price.query(f"author_name == '{auth}'")["price"].min()
    authors_stat.loc[i, "max_price"] = authors_price.query(f"author_name == '{auth}'")["price"].max()
    authors_stat.loc[i, "mean_price"] = authors_price.query(f"author_name == '{auth}'")["price"].mean()
    i += 1
authors_stat

author_name  min_price  max_price  mean_price
0    Тургенев      300.0      450.0  366.666667
1       Чехов      450.0      500.0  475.000000
2  Островский      290.0      370.0  330.000000

### * Задание 5

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая.
В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.
Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке.Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая",а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями,при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl".Затем загрузите из этого файла датафрейм и назовите его book_info2.Удостоверьтесь, что датафреймы book_info и book_info2 идентичны